{{- if .Values.smtp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postal.smtp.serviceAccountName" . }}
  labels:
    {{- include "postal.smtp.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.smtp.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
