apiVersion: v1
kind: Service
metadata:
  name: {{ include "postal.smtp.fullname" . }}-metrics
  labels:
    {{- include "postal.smtp.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.smtp.healthAndMetricsServerPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "postal.smtp.selectorLabels" . | nindent 4 }}
