apiVersion: v1
kind: Service
metadata:
  name: {{ include "postal.smtp.fullname" . }}
  labels:
    {{- include "postal.smtp.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.smtp.service.type }}
  ports:
  {{- if .Values.smtp.service.ports }}
  {{- range .Values.smtp.service.ports }}
    - port: {{ .port }}
      targetPort: 25
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
  {{- end }}
  {{- else }}
    - port: {{ .Values.smtp.service.port | default 25 }}
      targetPort: 25
      protocol: TCP
      name: smtp
  {{- end }}
  selector:
    {{- include "postal.smtp.selectorLabels" . | nindent 4 }}
