{{- if .Values.jobs.initialize.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postal.jobs.initialize.serviceAccountName" . }}
  labels:
    {{- include "postal.jobs.initialize.labels" . | nindent 4 }}
  {{- with .Values.jobs.initialize.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
