apiVersion: v1
kind: Service
metadata:
  name: {{ include "postal.worker.fullname" . }}
  labels:
    {{- include "postal.worker.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.healthAndMetricsServerPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "postal.worker.selectorLabels" . | nindent 4 }}
