{{- if not .Values.global.existingSecretName }}
{{- $key := genPrivateKey "rsa" }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "postal.fullname" . }}
  labels:
    {{- include "postal.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonsAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  signing-key: {{ $key | b64enc | quote }}
  rails-secret-key: {{ $key | b64enc | quote }}
{{- end }}
