{{- if .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postal.web.serviceAccountName" . }}
  labels:
    {{- include "postal.web.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.web.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
