apiVersion: v1
kind: Service
metadata:
  name: {{ include "postal.web.fullname" . }}
  labels:
    {{- include "postal.web.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.web.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postal.web.selectorLabels" . | nindent 4 }}
